// This file is generated by scripts/sync-hero-sequence.mjs.
// Do not edit manually. Add numeric SVG frames to the source folder and run npm run sync:hero-sequence.

export const heroSequenceFrames = [
  "/hero_sequence/1.svg",
  "/hero_sequence/2.svg",
  "/hero_sequence/3.svg",
  "/hero_sequence/4.svg",
  "/hero_sequence/5.svg",
  "/hero_sequence/6.svg",
  "/hero_sequence/7.svg",
  "/hero_sequence/8.svg",
  "/hero_sequence/9.svg",
  "/hero_sequence/10.svg",
  "/hero_sequence/11.svg"
] as const;
